#!/bin/bash

# Script d'installation pour LLDP Discovery sur Debian 12
# Auteur: Generated by GitHub Copilot
# Date: 2025-07-10

set -e  # Arrêter le script en cas d'erreur

echo "🚀 Installation de LLDP Discovery sur Debian 12"
echo "================================================"

# Couleurs pour l'affichage
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Fonction pour afficher des messages colorés
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Vérifier que le script est exécuté sur Debian
if ! grep -q "Debian" /etc/os-release; then
    print_error "Ce script est conçu pour Debian. Distribution détectée :"
    cat /etc/os-release | grep PRETTY_NAME
    exit 1
fi

print_success "Debian détecté, poursuite de l'installation..."

# Mise à jour du système
print_status "Mise à jour du système..."
sudo apt update && sudo apt upgrade -y

# Installation des paquets système nécessaires
print_status "Installation des paquets système..."
sudo apt install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    git \
    curl \
    wget \
    jq \
    ssh \
    nmap \
    build-essential \
    libssl-dev \
    libffi-dev

print_success "Paquets système installés"

# Vérifier la version de Python
PYTHON_VERSION=$(python3 --version | cut -d' ' -f2)
print_status "Version Python détectée: $PYTHON_VERSION"

if [[ $(echo "$PYTHON_VERSION" | cut -d'.' -f1) -lt 3 ]] || [[ $(echo "$PYTHON_VERSION" | cut -d'.' -f2) -lt 8 ]]; then
    print_error "Python 3.8 ou supérieur requis. Version actuelle: $PYTHON_VERSION"
    exit 1
fi

# Créer un environnement virtuel
print_status "Création de l'environnement virtuel..."
if [ -d "lldp-env" ]; then
    print_warning "L'environnement virtuel existe déjà"
    read -p "Voulez-vous le recréer ? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf lldp-env
        python3 -m venv lldp-env
    fi
else
    python3 -m venv lldp-env
fi

print_success "Environnement virtuel créé"

# Activer l'environnement virtuel
print_status "Activation de l'environnement virtuel..."
source lldp-env/bin/activate

# Mettre à jour pip
print_status "Mise à jour de pip..."
pip install --upgrade pip setuptools wheel

# Installer les dépendances Python
if [ -f "requirements.txt" ]; then
    print_status "Installation des dépendances Python..."
    pip install -r requirements.txt
    print_success "Dépendances Python installées"
else
    print_warning "Fichier requirements.txt non trouvé, installation manuelle..."
    pip install netmiko paramiko ansible pyaml
fi

# Installer les collections Ansible si le répertoire ansible existe
if [ -d "ansible" ]; then
    print_status "Installation des collections Ansible..."
    cd ansible
    if [ -f "requirements.yml" ]; then
        ansible-galaxy collection install -r requirements.yml
    else
        # Installation manuelle des collections essentielles
        ansible-galaxy collection install arubanetworks.arubaoss
        ansible-galaxy collection install community.general
    fi
    cd ..
    print_success "Collections Ansible installées"
fi

# Créer le répertoire de sortie s'il n'existe pas
if [ ! -d "output" ]; then
    mkdir -p output
    print_status "Répertoire 'output' créé"
fi

# Définir les permissions appropriées
chmod +x python/*.py 2>/dev/null || true
chmod +x ansible/*.yml 2>/dev/null || true

# Afficher les informations de fin d'installation
echo
print_success "🎉 Installation terminée avec succès !"
echo
echo "📋 Étapes suivantes :"
echo "1. Activez l'environnement virtuel :"
echo "   source lldp-env/bin/activate"
echo
echo "2. Configurez vos switches dans :"
echo "   - python/switches_config.json"
echo "   - ansible/inventory.ini"
echo
echo "3. Testez la connectivité :"
echo "   python3 python/test_connectivity.py"
echo
echo "4. Lancez la découverte LLDP :"
echo "   python3 python/lldp_discovery.py -v"
echo "   ou"
echo "   cd ansible && ansible-playbook -i inventory.ini lldp_discovery.yml"
echo
echo "📚 Consultez le README.md pour plus d'informations"
echo

# Créer un script d'activation rapide
cat > activate_env.sh << EOF
#!/bin/bash
# Script d'activation rapide de l'environnement LLDP Discovery
source lldp-env/bin/activate
echo "Environnement LLDP Discovery activé"
echo "Utilisez 'deactivate' pour quitter l'environnement"
EOF

chmod +x activate_env.sh
print_status "Script d'activation 'activate_env.sh' créé"

# Vérification finale
print_status "Vérification de l'installation..."
python3 -c "import netmiko, paramiko, yaml; print('✅ Modules Python importés avec succès')" || print_error "❌ Problème avec les modules Python"
ansible --version > /dev/null && print_success "✅ Ansible installé et fonctionnel" || print_warning "⚠️  Problème avec Ansible"

print_success "Installation vérifiée !"
