---
- name: Découverte LLDP sur switches Aruba 2530 et 6100
  hosts: aruba_switches
  gather_facts: yes
  vars:
    output_directory: "../output"
  
  tasks:
    - name: Créer le répertoire de sortie
      file:
        path: "{{ output_directory }}"
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Récupérer les informations LLDP neighbors
      arubanetworks.aos_switch.arubaoss_command:
        commands:
          - show lldp neighbors detail
      register: lldp_neighbors

    - name: Récupérer la table ARP
      arubanetworks.aos_switch.arubaoss_command:
        commands:
          - show arp
      register: arp_table

    - name: Récupérer les informations système
      arubanetworks.aos_switch.arubaoss_command:
        commands:
          - show system
      register: system_info

    - name: Parser les données LLDP
      set_fact:
        parsed_lldp: "{{ lldp_neighbors.stdout[0] | parse_lldp_neighbors }}"
        parsed_arp: "{{ arp_table.stdout[0] | parse_arp_table }}"
        switch_info: "{{ system_info.stdout[0] | parse_system_info }}"

    - name: Enrichir les données avec les informations ARP
      set_fact:
        enriched_neighbors: "{{ parsed_lldp | enrich_with_arp(parsed_arp) }}"

    - name: Préparer les données de sortie
      set_fact:
        switch_data:
          switch_ip: "{{ inventory_hostname }}"
          switch_model: "{{ switch_info.model | default('Unknown') }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          neighbors_count: "{{ enriched_neighbors | length }}"
          neighbors: "{{ enriched_neighbors }}"

    - name: Sauvegarder les résultats par switch
      copy:
        content: "{{ switch_data | to_nice_json }}"
        dest: "{{ output_directory }}/{{ inventory_hostname }}_lldp_discovery.json"
      delegate_to: localhost

    - name: Ajouter aux résultats globaux
      set_fact:
        all_switches_data: "{{ all_switches_data | default({}) | combine({inventory_hostname: switch_data}) }}"

- name: Consolider les résultats
  hosts: localhost
  gather_facts: yes
  run_once: true
  tasks:
    - name: Créer le rapport consolidé
      set_fact:
        consolidated_report:
          discovery_timestamp: "{{ ansible_date_time.iso8601 }}"
          switches: "{{ hostvars | dict2items | selectattr('value.all_switches_data', 'defined') | map(attribute='value.all_switches_data') | list | combine }}"
          summary:
            total_switches: "{{ groups['aruba_switches'] | length }}"
            successful_connections: "{{ hostvars | dict2items | selectattr('value.all_switches_data', 'defined') | list | length }}"
            total_neighbors: "{{ hostvars | dict2items | selectattr('value.all_switches_data', 'defined') | map(attribute='value.all_switches_data') | map('dict2items') | flatten | map(attribute='value.neighbors_count') | map('int') | sum }}"

    - name: Sauvegarder le rapport consolidé
      copy:
        content: "{{ consolidated_report | to_nice_json }}"
        dest: "{{ output_directory }}/consolidated_lldp_discovery.json"
